// ─── Mock AI Copilot Data ─────────────────────────────────────────────────────
// Canned responses for the AI Copilot prototype.
// Extracted from AICopilot.tsx to separate concerns.
// Will be replaced by a real LLM call (with RAG over case/prediction data) in integration phase.

import type { CopilotSuggestedPrompt, CopilotMessage } from '../types';

export const SUGGESTED_PROMPTS: CopilotSuggestedPrompt[] = [
  { id: 'p1', text: 'Why is Gurugram currently top-ranked?', category: 'prediction' },
  { id: 'p2', text: 'Show the transaction trail for case NCRP-26-81942.', category: 'case' },
  { id: 'p3', text: 'Which mule account appears across multiple cases?', category: 'network' },
  { id: 'p4', text: 'Summarize this case for the report.', category: 'case' },
  { id: 'p5', text: 'What OSINT signals support the Gurugram prediction?', category: 'osint' },
  { id: 'p6', text: 'How confident is the prediction and why?', category: 'prediction' },
];

// Canned response map (promptId → response)
export const CANNED_RESPONSES: Record<string, CopilotMessage> = {
  p1: {
    role: 'assistant',
    content:
      'Gurugram Sector 29 is currently ranked #1 because of a convergence of three signals:\n\n' +
      '1. **Transaction pattern**: Mule account XXXX9234 (SBI) received ₹1.1L at 13:54 and has a historical cash-out window of 45–90 min in this geographic cluster.\n\n' +
      '2. **Risk registry match**: XXXX9234 is flagged in 7 prior complaints — it is a **Persistent Risk Entity** in the Gurugram cluster.\n\n' +
      '3. **OSINT corroboration**: 2 verified signals reference ATM activity in Gurugram Sector 29 in the past 6 hours.\n\n' +
      '*Note: This explanation is generated by the prototype explainability layer, not a deployed ML model.*',
    sources: ['Transaction trail: NCRP-26-81942', 'Risk Registry: XXXX9234', 'OSINT: OST-001, OST-003'],
    timestamp: 'now',
  },
  p2: {
    role: 'assistant',
    content:
      'Transaction trail for **NCRP-26-81942**:\n\n' +
      '• **13:47** — Victim (HDFC XXXX1234) → Account A (HDFC XXXX7821) · ₹1.8L\n' +
      '• **13:51** — Account A → Mule B (Paytm XXXX3294) · ₹1.4L\n' +
      '• **13:54** — Mule B → Mule C/Hub (SBI XXXX9234) · ₹1.1L\n' +
      '• **PREDICTED** — Mule C → Gurugram ATM Cluster · ₹1.1L\n\n' +
      'Total elapsed: 12 minutes from complaint to final known hop. Typical cash-out window for this typology is 45–90 minutes.',
    sources: ['Transaction data: NCRP-26-81942'],
    timestamp: 'now',
  },
  p3: {
    role: 'assistant',
    content:
      'Account **XXXX9234 (SBI)** is the highest-risk shared entity in the current case pool.\n\n' +
      'It appears in **7 complaints** over the last 60 days, making it the most persistent mule hub in the active dataset. It has been flagged in:\n' +
      '• NCRP-26-81942 (current · Investment Fraud)\n' +
      '• NCRP-26-78901 (resolved · UPI Fraud)\n' +
      '• NCRP-26-79334 (resolved · Investment Fraud)\n' +
      '• 4 additional older complaints\n\n' +
      'Account **XXXX3294 (Paytm)** also appears across 4 complaints and is classified as a Persistent Risk Entity.',
    sources: ['Fraud Network: XXXX9234', 'Risk Registry'],
    timestamp: 'now',
  },
  p4: {
    role: 'assistant',
    content:
      '**Case Summary: NCRP-26-81942**\n\n' +
      'Victim reported an investment fraud of ₹4,80,000 at 13:42 IST today from New Delhi. ' +
      'Funds were routed through 3 accounts (HDFC → Paytm → SBI) over 12 minutes. ' +
      'The final mule hub (SBI XXXX9234) is a known persistent entity with 7 prior complaint appearances.\n\n' +
      'TRINETRA predicts **Gurugram Sector 29** as the likely cash-out zone (87% confidence, prototype). ' +
      'Recoverability window: approximately 48 minutes remaining.\n\n' +
      'Recommended action: **Auto Alert** — Notify HDFC Bank fraud desk and local LEA in Gurugram.',
    sources: ['Case: NCRP-26-81942', 'Prediction Engine', 'Risk Registry'],
    timestamp: 'now',
  },
  p5: {
    role: 'assistant',
    content:
      'Two verified OSINT signals support the Gurugram prediction:\n\n' +
      '1. **OST-001** (The Hindu): "NCR mule account network dismantled; 12 arrested in Gurugram" — 96% credibility. Matches current zone and typology.\n\n' +
      '2. **OST-003** (Fraud DB): ATM cluster Gurugram Sector 29 flagged in 3 previous NCRP complaints — 88% credibility.\n\n' +
      'Note: OSINT supports investigation and is **not** a primary input to the prediction score in the current prototype. It will be integrated as a weighted signal in the model training phase.',
    sources: ['OSINT: OST-001', 'OSINT: OST-003'],
    timestamp: 'now',
  },
  p6: {
    role: 'assistant',
    content:
      'Current prediction confidence for NCRP-26-81942 is **87%** after 2 observed transaction hops (prototype simulation).\n\n' +
      'Evidence breakdown:\n' +
      '• 29% — 3 accounts linked to prior NCRP fraud trails\n' +
      '• 23% — Transaction velocity matches known cash-out pattern\n' +
      '• 18% — Destination geographically linked to Gurugram cluster\n' +
      '• 13% — Similar fraud cases cashed out within 90 minutes\n' +
      '• 8% — OSINT corroboration (3 signals)\n\n' +
      'The confidence increased from 31% (initial prior) → 48% (after Hop 1) → 87% (after Hop 2). ' +
      'This narrowing is the core TRINETRA prediction evolution.',
    sources: ['Prediction Engine', 'Explainability Layer'],
    timestamp: 'now',
  },
};
